### ISSUE TITLE
Can it be used to run the m3u8 protected by nginx valid_referers

### ISSUE THREAD

**Issue by cassahd7** [michaljanocko/pancors#4]
Can it be used to run the m3u8 protected by nginx valid_referers
pleas help

**Comment by michaljanocko** [comment]
It should work if we are talking about just downloading the .m3u8 file (which happens over HTTP[S]). However, if it is protected by checking the _Referer_ header, then there is nothing you can do now. We could technically add the referer header as one of the parameters. Also, if you want to stream the video through _PanCORS_—that is currently not possible. _PanCORS_ is only an HTTP proxy so streaming is possible only through HTTP. Could you elaborate more on what your intentions are?

> I'm not very experienced with streaming video, so correct me if I'm wrong on any of this.

**Comment by cassahd7** [comment]
Look, I just want to fake a header
nginx say
The ngx_http_referer_module module is used to block access to a site for requests with invalid values in the “Referer” header field. It should be kept in mind that fabricating a request with an appropriate “Referer” field value is quite easy, and so the intended purpose of this module is not to block such requests thoroughly but to block the mass flow of requests sent by regular browsers. It should also be taken into consideration that regular browsers may not send the “Referer” field even for valid requests.

**Comment by cassahd7** [comment]
Because I want to embed content protected by valid_referers

**Comment by michaljanocko** [comment]
OK, I hoped it would be this as I don't know much about video streaming. I'm gonna add this as a feature for you.

**Comment by cassahd7** [comment]
Well thank you very much Broo
and Sorry for the inconvenience

**Comment by cassahd7** [comment]
Where do I put Referer
for example
google.com

**Comment by michaljanocko** [comment]
Well, I still haven't written the tests for this but on this branch, you should be able to do just `pancors.url/?url=your_url&referer=your_referer`. Actually, do you have a site that I can test this against?

**Comment by michaljanocko** [comment]
Alright, done! Enjoy and good luck on whatever you're working on!
